name: Release Beta

on:
  push:
    branches:
      - v3.0.0

env:
  FORCE_COLOR: true

jobs:
  release:
    name: Release Beta
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'khulnasoft/openref' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - uses: actions/setup-node@v2
        with:
          node-version: "*"
          registry-url: "https://registry.npmjs.org"
      - name: Release Beta
        run: npx ts-node --transpile-only scripts/publish-beta.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
